### ISSUE TITLE
Add your plugins to awesome-yazi

### ISSUE THREAD

**Issue by AnirudhG07** [Ape/simple-status.yazi#1]
Hey, I noticed your plugins are up on yazi-rs GitHub, you can also add all ur plugins added there to [awesome-yazi](https://github.com/AnirudhG07/awesome-yazi) list! thanks.

**Comment by Ape** [comment]
Could you add them for me?

**Comment by AnirudhG07** [comment]
Yes I can, although would feel nice to have other people add in. For any more plugins later on, do add them in the repo. thanks!
